name: Deploy to environment

on:
  workflow_dispatch:
  schedule:
    - cron: "58 17 * * *"

jobs:
  deploy_into_dev_server:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Commands
        uses: appleboy/ssh-action@master
        with:
          host: 34.228.78.13
          username: ec2-user
          key: ${{ secrets.REACT_SERVER_PRIVATE_KEY }}
          script: |
            sudo docker stop REACT_SERVICE
            sudo docker rm REACT_SERVICE
            sudo docker run -d -p 8080:80 --name REACT_SERVICE cesarill/react-app:latest